version: '3.8'

services:
  db:
    image: postgres:15
    container_name: bitespeed-db
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bitespeed
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
